# Generated by Django 3.1.7 on 2021-03-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='building_data',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='hourly_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption', models.CharField(max_length=30)),
                ('meter_id', models.CharField(max_length=30)),
                ('reading_date_time', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='meter_data',
            fields=[
                ('building_id', models.CharField(max_length=30)),
                ('fuel', models.CharField(max_length=30)),
                ('unit', models.CharField(max_length=30)),
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
    ]
